permalink: /:categories/:year/:month/:day/:title/
static_url: https://nodebox-workshops.s3.amazonaws.com/media/
highlighter: rouge
multiviews: true
collections:
  workshops:
    output: true
    permalink: /:name
exclude:
  - README.md
  - Rakefile
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
