permalink: /:categories/:year/:month/:day/:title/
thumb_url: https://res.cloudinary.com/dgunfvbce/image/fetch/w_440/https://nodebox-workshops.s3.amazonaws.com/media/
static_url: https://nodebox-workshops.s3.amazonaws.com/media/
highlighter: rouge
multiviews: true
collections:
  workshops:
    output: true
    permalink: /:name
exclude:
  - README.md
  - Rakefile
  - _convert/
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
